apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: scan-document

spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: scan-document
 minReplicas: 1
 maxReplicas: 9
 targetCPUUtilizationPercentage: 80