name: Deploy on release - Kubernetes
on:
  release:
    types:
    - 'created'
jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/scanocr
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Build and push Docker image based on the changes
      run: |
        cp params.yaml src
        docker build src --tag "$IMAGE_NAME:$SHORT_SHA"
        docker tag "$IMAGE_NAME:$SHORT_SHA" "$IMAGE_NAME:latest"
        docker push "$IMAGE_NAME:$SHORT_SHA"
        docker push "$IMAGE_NAME:latest"
        
    - name: Set up Kustomize
      working-directory: k8s/
      run: |-
        curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.1.2/kustomize_v4.1.2_linux_amd64.tar.gz
        tar -zxvf kustomize.tar.gz
        chmod u+x ./kustomize

    - name: Deploy to GKE
      working-directory: k8s/
      run: |
        gcloud container clusters get-credentials thuyen-test-k8s --zone us-central1-c --project torrient
        ./kustomize edit set image $IMAGE_NAME:$SHORT_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/scan-document
        kubectl get services -o wide